Sort commandline options

diff --git a/mgitstatus b/mgitstatus
--- a/mgitstatus
+++ b/mgitstatus
@@ -15,15 +15,15 @@ repositories. By default, mgitstatus scans two directories deep. This can be
 changed with the -d (--depth) option.  If DEPTH is 0, the scan is infinitely
 deep.
 
-  --version        Show version
-  -w               Warn about dirs that are not Git repositories
-  -e               Exclude repos that are 'ok'
-  -f               Do a 'git fetch' on each repo (slow for many repos)
-  --throttle SEC   Wait SEC seconds between each 'git fetch' (-f option)
   -c               Force color output (preserve colors when using pipes)
   -d, --depth=2    Scan this many directories deep
-  --no-depth       Do not recurse into directories (incompatible with -d)
+  -e               Exclude repos that are 'ok'
+  -f               Do a 'git fetch' on each repo (slow for many repos)
   --flatten        Show only one status per line
+  --no-depth       Do not recurse into directories (incompatible with -d)
+  --throttle SEC   Wait SEC seconds between each 'git fetch' (-f option)
+  --version        Show version
+  -w               Warn about dirs that are not Git repositories
 
 You can limit output with the following options:
 
@@ -58,16 +58,19 @@ while [ -n "$1" ]; do
     # Stop reading when we've run out of options.
     [ "$(printf "%s" "$1" | cut -c 1)" != "-" ] && break
 
-    if [ "$1" = "--version" ]; then
-        echo "v$VERSION"
-        exit 0
+    if [ "$1" = "-c" ]; then
+        FORCE_COLOR=1
     fi
-    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
-        usage
-        exit 1
-    fi
-    if [ "$1" = "-w" ]; then
-        WARN_NOT_REPO=1
+    if [ "$1" = "-d" ] || [ "$1" = "--depth" ]; then
+        DEPTH="$2"
+        echo "$DEPTH" | grep -E "^[0-9]+$" > /dev/null 2>&1
+        IS_NUM="$?"
+        if [ "$IS_NUM" -ne 0 ]; then
+            echo "Invalid value for 'depth' (must be a number): $DEPTH" >&2
+            exit 1
+        fi
+        # Shift one extra param
+        shift
     fi
     if [ "$1" = "-e" ]; then
         EXCLUDE_OK=1
@@ -75,11 +78,12 @@ while [ -n "$1" ]; do
     if [ "$1" = "-f" ]; then
         DO_FETCH=1
     fi
-    if [ "$1" = "-c" ]; then
-        FORCE_COLOR=1
-    fi
     if [ "$1" = "--flatten" ]; then
         FLATTEN=1
+    fi
+    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+        usage
+        exit 1
     fi
     if [ "$1" = "--no-push" ]; then
         NO_PUSH=1
@@ -118,16 +122,12 @@ while [ -n "$1" ]; do
         # Shift one extra param
         shift
     fi
-    if [ "$1" = "-d" ] || [ "$1" = "--depth" ]; then
-        DEPTH="$2"
-        echo "$DEPTH" | grep -E "^[0-9]+$" > /dev/null 2>&1
-        IS_NUM="$?"
-        if [ "$IS_NUM" -ne 0 ]; then
-            echo "Invalid value for 'depth' (must be a number): $DEPTH" >&2
-            exit 1
-        fi
-        # Shift one extra param
-        shift
+    if [ "$1" = "--version" ]; then
+        echo "v$VERSION"
+        exit 0
+    fi
+    if [ "$1" = "-w" ]; then
+        WARN_NOT_REPO=1
     fi
 
     shift
