Added option to throttle git fetches.

diff --git a/mgitstatus b/mgitstatus
--- a/mgitstatus
+++ b/mgitstatus
@@ -8,19 +8,20 @@ DEBUG=0
 usage () {
     cat << EOF >&2
     
-Usage: $0 [--version] [-w] [-e] [-f] [--no-X] [-d/--depth=2] [DIR [DIR]...]
+Usage: $0 [--version] [-w] [-e] [-f] [--no-X] [--throttle SEC][-d/--depth=2] [DIR [DIR]...]
 
 mgitstatus shows uncommitted, untracked and unpushed changes in multiple Git
 repositories.  By default, mgitstatus scans two directories deep. This can be
 changed with the -d (--depth) option.  If DEPTH is 0, the scan is infinitely
 deep.
 
-  --version      Show version
-  -w             Warn about dirs that are not Git repositories
-  -e             Exclude repos that are 'ok'
-  -f             Do a 'git fetch' on each repo (slow for many repos)
-  -c             Force color output (preserve colors when using pipes)
-  -d, --depth=2  Scan this many directories deep
+  --version        Show version
+  -w               Warn about dirs that are not Git repositories
+  -e               Exclude repos that are 'ok'
+  -f               Do a 'git fetch' on each repo (slow for many repos)
+  -c               Force color output (preserve colors when using pipes)
+  --throttle SEC   Wait SEC seconds between each 'git fetch' (-f option)
+  -d, --depth=2    Scan this many directories deep
 
 You can limit output with the following options:
 
@@ -45,6 +46,7 @@ NO_UPSTREAM=0
 NO_UNCOMMITTED=0
 NO_UNTRACKED=0
 NO_STASHES=0
+THROTTLE=0
 DEPTH=2
 
 while [ -n "$1" ]; do
@@ -89,6 +91,17 @@ while [ -n "$1" ]; do
     if [ "$1" = "--no-stashes" ]; then
         NO_STASHES=1
     fi
+    if [ "$1" = "--throttle" ]; then
+        THROTTLE="$2"
+        echo "$THROTTLE" | grep -E "^[0-9]+$" > /dev/null 2>&1
+        IS_NUM="$?"
+        if [ "$IS_NUM" -ne 0 ]; then
+            echo "Invalid value for 'throttle' (must be a number): $THROTTLE" >&2
+            exit 1
+        fi
+        # Shift one extra param
+        shift
+    fi
     if [ "$1" = "-d" ] || [ "$1" = "--depth" ]; then
         DEPTH="$2"
         echo "$DEPTH" | grep -E "^[0-9]+$" > /dev/null 2>&1
@@ -103,6 +116,7 @@ while [ -n "$1" ]; do
 
     shift
 done
+
 
 if [ -t 1 ] || [ "$FORCE_COLOR" -eq 1 ]; then
     # Our output is not being redirected, so we can use colors.
@@ -268,6 +282,11 @@ for DIR in "${@:-"."}"; do
         # Print the output, unless repo is 'ok' and -e was specified
         if [ "$IS_OK" -ne 1 ] || [ "$EXCLUDE_OK" -ne 1 ]; then
             printf "${PROJ_DIR}: $STATUS_NEEDS\n"
+        fi
+
+        # Throttle if requested
+        if [ "$DO_FETCH" -eq 1 ] && [ "$THROTTLE" -ne 0 ]; then
+            sleep "$THROTTLE"
         fi
     done
 done
